image: nexus.spaceapplications.com/repository/infuse/cdff-dev-ci:1.7.3

stages:
  - fetch_test

fetch_test:
  stage : fetch_test
  script:
      - git clone --depth 1 https://gitlab-ci-token:pVUF6xEhoz2kgWAUyyCr@gitlab.spaceapplications.com/InFuse/CDFF.git
      - cd build_tools/ && ./get_cdff_artifacts.sh && cd ../
      - export CDFFPATH="${PWD}/CDFF"
      - python3 setup.py build_ext -i
      - nosetests -sv
