image:  nexus.spaceapplications.com/repository/infuse/cdff-dev-ci:1.8.14

stages:
  - fetch_test

fetch_test:
  stage : fetch_test
  script:
      - source /tmp/infuse/env.sh
      - export CDFFPATH="/tmp/infuse/cdff/CDFF"
      - python3 setup.py build_ext -i
      - nosetests -sv cdff_dev/test/ cdff_dev/extensions/ test/
