image: nexus.spaceapplications.com/repository/infuse/cdff-dev-ci:1.6.5.3

stages:
  - fetch_cdff
  - build_cdff_dev
  - test

fetch_cdff:
  stage : fetch_cdff
  script:
      - git clone --depth 1 https://gitlab-ci-token:pVUF6xEhoz2kgWAUyyCr@gitlab.spaceapplications.com:InFuse/Infuse/CDFF.git
      - make build_cdff
  artifacts:
    paths:
      - CDFF/Common/Types/C
      - CDFF/DFNs/DFNCommonInterface.hpp

build_cdff_dev:
  stage : build_cdff_dev
  script:
      - python3 setup.py build_ext -i
  artifacts:
    paths:
      - .

test:
  stage : test
  variables:
    PYTHONPATH: install/lib/python3.5/site-packages
  script:
      - mv cdff_dev cdff_dev_tests; nosetests -sv
