image: nexus.spaceapplications.com/repository/infuse/cdff_dev:1.6.4

stages:
  - fetch_cdff
  - build_cdff_dev
  - test

fetch_cdff:
  stage : fetch_cdff
  script:
      - git clone --depth 1 https://gitlab-ci-token:pVUF6xEhoz2kgWAUyyCr@gitlab.spaceapplications.com:InFuse/Infuse/CDFF.git
      - make build_cdff
  artifacts:
    paths:
      - CDFF

build_cdff_dev:
  stage : build_cdff_dev
  script:
      - python3 setup.py build_ext -i

test:
  stage : test
  script:
      - make test
