image: h2020infuse/cdff-dev-ci:1.8.2

stages:
  - fetch_test

fetch_test:
  stage : fetch_test
  script:
      - git config --global user.email infuse@example.com
      - git config --global user.name InFuse
      - git clone --depth 1 https://cdff-dev:cdff-dev@gitlab.spaceapplications.com/InFuse/CDFF.git
      - cd build_tools/ && ./get_cdff_artifacts.sh && cd ../
      - source /tmp/infuse/env.sh
      - export CDFFPATH="${PWD}/CDFF"
      - amake
      - nosetests -sv cdff_dev/test test/
