image: nexus.spaceapplications.com/repository/infuse/cdff-dev-ci:1.7.3

stages:
  - fetch_test

fetch_test:
  stage : fetch_test
  script:
      - source /opt/infuse/env.sh
      - export CDFFPATH="/opt/infuse/cdff/CDFF"
      - python3 setup.py build_ext -i
      - nosetests -sv
