image: nexus.spaceapplications.com/repository/infuse/cdff-dev-ci:1.7

stages:
  - fetch_test

fetch_test:
  stage : fetch_test
  script:
      - repositories=${PWD}
      - git clone --depth 1 https://gitlab-ci-token:pVUF6xEhoz2kgWAUyyCr@gitlab.spaceapplications.com/InFuse/CDFF.git
      - git clone --depth 1 https://gitlab-ci-token:pVUF6xEhoz2kgWAUyyCr@gitlab.spaceapplications.com/InFuse/CDFF_dev.git
      - cd CDFF_dev && build_tools/get_cdff_artifacts.sh
      - CDFFPATH=${repositories}/CDFF python3 setup.py build_ext -i
      - CDFFPATH=${repositories}/CDFF nosetests -sv
