image: nexus.spaceapplications.com/repository/infuse/cdff-dev-ci:1.6.5.5

stages:
  - build_cdff_dev
  - test

fetch_cdff:
  stage : build_cdff_dev
  script:
      - echo -n "CDFF" > cdffpath
      - python3 setup.py build_ext -i
  artifacts:
    paths:
      - .

test:
  stage : test
  script:
      - nosetests -sv
