image: h2020infuse/cdff-dev-ci:1.8.4

stages:
  - fetch_test

fetch_test:
  stage : fetch_test
  script:
      - source /tmp/infuse/env.sh
      - export CDFFPATH="/tmp/infuse/cdff/CDFF"
      - build_tools/get_cdff_artifacts.sh
      - python3 setup.py build_ext -i
      - nosetests -sv cdff_dev/test/ test/
