FROM repository/infuse/cdff-dev-ci:1.6.5.4

WORKDIR /builds/InFuse
RUN git clone --depth 1 https://gitlab-ci-token:pVUF6xEhoz2kgWAUyyCr@gitlab.spaceapplications.com:InFuse/Infuse/CDFF_dev.git
WORKDIR /builds/InFuse/CDFF_dev
RUN echo -n "/builds/InFuse/CDFF" > cdffpath
RUN pip3 install -e .

LABEL maintainer="Alexander.Fabisch@dfki.de"

LABEL version="1.6.5.4"
